name: Unit Tests

env:
  NEXT_PUBLIC_APP_URL: http://localhost:3000
  NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME: cloudinary-cloud-name

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Run Unit Tests
        run: npm run test
